### ISSUE TITLE
0.0.1 release

### ISSUE THREAD

**Issue by cosmicBboy** [cosmicBboy/langgym#1]
### Tasks

- [ ] Support local and small (cheaper) models
- [ ] Create routines for multi-agent environment
- [ ] Create meta environment that supports agent traversal from multiple environments
